name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: binary-linux
            binary_path: ./target/x86_64-unknown-linux-musl/release/deploy-helper
            upload_name: deploy-helper-linux
          # - os: macos-latest
          #   artifact_name: binary-macos
          #   binary_path: ./target/release/deploy-helper
          #   upload_name: deploy-helper-macos
          # - os: windows-latest
          #   artifact_name: binary-windows
          #   binary_path: ./target/release/deploy-helper.exe
          #   upload_name: deploy-helper-windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Build for macOS
      if: matrix.os == 'macos-latest'
      run: cargo build --release

    - name: Build for linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y musl-tools
        rustup target add x86_64-unknown-linux-musl
        cargo build --release --target x86_64-unknown-linux-musl

    - name: Rename binary
      run: mv ${{ matrix.binary_path }} ${{ matrix.upload_name }}

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ matrix.upload_name }}
        generate_release_notes: true
